### PR TITLE
Add VAULTED_ENV_EXPIRATION var

### PR DESCRIPTION
**Pull request by miquella**

### CODE REVIEW

**Comment by drusellers** [comment]
YAS!! I was just looking for this feature. 👏

**Comment by miquella** [comment]
@drusellers: we should be cutting a release this week that will include this :)

**Comment by drusellers** [comment]
Awesome!! That will complete my ZSH shell of awesome.

**Comment by miquella** [comment]
@drusellers: there may be one more thing to consider including in your shell of awesome (if you assume roles, that is) over in #71.

**Pull request merged**
